la_liga:
  league_id: 140
  scope: "domestic"
  region: "Europe"

champions_league:
  league_id: 2
  scope: "continental"
  region: "Europe"

brasileirao:
  league_id: 71
  scope: "domestic"
  region: "South America"

libertadores:
  league_id: 13
  scope: "continental"
  region: "South America"